BEGIN;

CREATE TABLE IF NOT EXISTS "list"(
  id UUID PRIMARY KEY,
  name VARCHAR(60) NOT NULL,
  creation_date TIMESTAMP WITH TIME ZONE NOT NULL,
  archivation_date TIMESTAMP WITH TIME ZONE
);

COMMIT;
