name: Quality check

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup project
        uses: actions/setup-api-action

      - name: Build
        run: go build -v .

      - name: Unit tests
        run: go test -v ./...
